#!/bin/bash

#ChIP-Seq preparation code for single cell
#this script is prepared by Ruslan Al-Ali
#2018-2019



echo “Hello”




for entry in `ls AS*`; do
    clumpify.sh in=$entry out=dedup_$entry dedupe
    echo "Done $entry" 
done;



python xclean.py



for entry in `ls clean*`; do
    bowtie2 -p 4 -x /home/ros/Desktop/NCT_projects/Genome37.13/bt13 -U $entry | samtools view -bS -  | samtools sort - | samtools rmdup -Ss - $entry.bam 
    samtools index $entry.bam $entry.bam.bai
    echo "Done $entry" 
done;


for entry in `ls *.bam`; do
    samtools view -b $entry chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22 chrX > std_$entry
    samtools index std_$entry
    echo "Done $entry" 
done;


for entry in `ls s*.bam`; do
	SUBSTRING=$(echo $entry| cut -d'_' -f 4)
	makeTagDirectory $SUBSTRING -keepAll $entry
	findPeaks $SUBSTRING  -style histone -o auto -minDist 10000 -size 10000    
	pos2bed.pl $SUBSTRING/regions.txt > $SUBSTRING.bed
	annotatePeaks.pl $SUBSTRING.bed hg19 > annutate_$SUBSTRING.tsv
    	samtools idxstats $entry >> index_stats.txt
    echo "Done $entry" 
done;

